server:
  port: 8080
spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      topic: product-inventory
      forward-to: fulfillment-station
      group-id: group-id
      auto-start: true
      auto-offset-reset: earliest
      enable-auto-commit: true
      isolation-level: read_committed
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: localhost:9092
      topic: product-inventory
      enable-idempotence: true
      transaction-id-prefix: tx-
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer